<script src="<?= publicdir('vendor/jquery.min.js') ?>"></script>
<script src="<?= publicdir('vendor/bootstrap.min.js') ?>"></script>
<script src="<?= publicdir('vendor/underscore-min.js') ?>"></script>
<script src="<?= publicdir('vendor/modernizr-custom.js') ?>"></script>
<script src="<?= publicdir('vendor/isMobile.min.js') ?>"></script>
<script src="<?= publicdir('vendor/jquery.nicescroll.min.js') ?>"></script>
<script src="<?= publicdir('vendor/jquery.mask.min.js') ?>"></script>
<script src="<?= publicdir('vendor/jquery.validate.min.js') ?>"></script>
<?php if ($page == 'game'): ?>
	<script src="<?= publicdir('js/game.js') ?>"></script>
<?php endif; ?>
<script src="<?= publicdir('js/main.js') ?>"></script>