<header class="navbar navbar-fixed-top" id="header" role="banner">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar"
                    aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand">
                <span>По будням в 20:15</span>
                <img src="<?= publicdir('images/logo.png') ?>">
            </a>
            <div class="header__promo">
                <img src="<?= publicdir('images/rostelekom-logo-big.svg') ?>">
            </div>
        </div>
        <?php include "nav.phtml" ?>
    </div>
</header>