<header class="header">
    <div class="container">
        <nav class="navbar navbar-default navbar-default--header" role="navigation">
            <ul class=" nav navbar-nav">
                <li><a href="#">Главная</a></li>
                <li><a href="#">О проекте</a></li>
                <li><a href="#">Как смотреть</a></li>
                <li><a href="#">Играть</a></li>
                <li><a href="#">Рейтинг</a></li>
                <li><a href="#">Правила</a></li>
            </ul>
        </nav>
    </div>
</header>