<nav id="bs-navbar" class="collapse navbar-collapse width">
	<a class="nav-close" data-target="#bs-navbar" data-toggle="collapse"><i class="icon icon-cross"></i></a>
	<ul class="nav navbar-nav">
		<li class="active"><a href="/">Главная</a></li>
		<li><a href="#">О проекте</a></li>
		<li><a href="#">Как смотреть</a></li>
		<li><a href="#">Играть</a></li>
		<li><a href="#">Рейтинг</a></li>
		<li><a href="#">Правила</a></li>
	</ul>
</nav>
