<div id="disclamer" class="modal fade disclamer" tabindex="-1" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">
				<img class="disclamer__img" src="<?= publicdir('images/rotate-me.png') ?>">
				<div class="disclamer__text">Переверните ваше устройство в горизонтальное положение</div>
				<button type="button" class="btn btn-primary disclamer__btn" data-dismiss="modal">OK</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->