<section class="page-caption">
    <img class="page-caption_logo" src="<?= publicdir('images/logo_1.png') ?>"/>
</section>
<section class="error">
    <div class="error__logo"><img src="<?= publicdir('images/logo_2.png') ?>"></div>
    <div class="error__title">
        <h1>404</h1>
    </div>
    <div class="error__text">
        <h2>Такой страницы не существует.</h2>
        <span>Лучше поучаствуй в <a href="#">нашем конкурсе</a></span>
    </div>
</section>