<section class="page-caption">
        <a href="/" class="navbar-brand">
            <span>По будням в 20:15</span>
            <img src="<?= publicdir('images/logo.png') ?>">
        </a>
</section>
<section class="error">
    <div class="error__logo"><img src="<?= publicdir('images/logo.png') ?>"></div>
    <div class="error__title">
        <h1>404</h1>
    </div>
    <div class="error__text">
        <h2>Такой страницы не существует.</h2>
        <span>Лучше поучаствуй в <a href="#">нашем конкурсе</a></span>
    </div>
</section>