<section class="page-caption">
    <img class="page-caption_logo" src="<?= publicdir('images/logo_1.png') ?>"/>
    <div class="page-caption__text">
        <h2>О проекте</h2>
    </div>
    <div class="page-caption__promo">
        <img src="<?= publicdir('images/rostelekom-logo.svg') ?>">
    </div>
</section>
<section class="page-content">
    <div class="bs-example" data-example-id="responsive-embed-16by9-iframe-youtube">
        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="//www.youtube.com/embed/zpOULjyy-n8?rel=0" allowfullscreen=""></iframe>
        </div>
    </div>
    <p>Среди героев «Уандерлэнда» кипят нешуточные страсти. Они влюбляются, изменяют, страдают и ненавидят. А хорошо ли вы чувствуете
        эмоции и переживания других людей? Предлагаем вам посмотреть три сцены из сериала и угадать, какие чувства испытывают персонажи.
        А в суперигре вы сможете применить свои навыки на других участниках проекта!</p>
        <span>Самым быстрым и результативным — летние призы от FOX Life!</span>
    <a href="#" class="btn btn-primary page-content__btn">Играть</a>
</section>