<?php // example of including a block:
// include "src/views/blocks/block-name.phtml" ?>

<?php include "src/views/blocks/page-caption.phtml" ?>

<section class="input-block">
    <?php include "src/views/blocks/summer-win.phtml" ?>
    <p>Смотри сериал <b>Уандерлэнд</b>, угадывай эмоции персонажей и выигрывай летние призы <br> от FOX Life!</p>
    <a href="#" class="btn btn-primary input-block__btn">Играть</a>
</section>
<div class="share share--desktop">
    <span class="share__text">Поделиться:</span>
    <div class="ya-share2" data-services="vkontakte,facebook"></div>
</div>