<?php // example of including a block:
// include "src/views/blocks/block-name.phtml" ?>

<section class="page-caption">

    <div class="page-caption__text">
        <span>Лето любви на <b>FOX Life</b></span>
    </div>
</section>
<section class="input-block">
    <p>Смотри сериал <b>Wonderland</b>, угадывай эмоции персонажей и выигрывай летние призы от FOX Life!</p>
    <a href="#" class="btn btn-primary input-block__btn">Играть</a>
</section>
<div class="share share--desktop">
    <span class="share__text">Поделиться:</span>
    <div class="ya-share2" data-services="vkontakte,facebook"></div>
</div>