<?php // example of including a block:
// include "src/views/blocks/block-name.phtml" ?>
<?php
include "src/views/blocks/scene-header.phtml" ?>
<?php
include "src/views/blocks/heart-blocks.phtml" ?>
<?php 
    include "src/views/blocks/authorization.phtml" ?>

<a class="btn btn-lg btn-success"
   href="#" data-toggle="modal"
   data-target="#superGame">Супер игра</a>
<?php
//include "src/views/blocks/supergame.phtml" ?>
<?php
include "src/views/blocks/supergame.phtml" ?>

<?php
//include "src/views/blocks/description.phtml" ?>

