<section class="page-caption">
    <div class="page-caption__logo">
        <img src="<?= publicdir('images/logo_1.png') ?>"/>
    </div>
    <div class="page-caption__text">
        <h2>Рейтинги <br>
            <span>Подведение итогов состоится 29 июня</span>
       </h2>
    </div>
    <div class="page-caption__promo">
        <img src="<?= publicdir('images/rostelekom-logo-small.svg') ?>"><br>
        <span class="white">Ростелеком</span>
    </div>
</section>
<section class="page-content">
        <div class="rating">
            <div class="content-table">
                
                <div class="content-table__row on-top">
                    <div class="content-table__cell">1</div>
                    <div class="content-table__cell">
                        <div class="content-table__img"
                             style="background-image: url(<?= publicdir('images/players/photo_1.jpg') ?>)"></div>
                        <span>Natzu Dragnil</span>
                    </div>
                    <div class="content-table__cell">500</div>
                </div>

                <div class="content-table__row on-top">
                    <div class="content-table__cell">2</div>
                    <div class="content-table__cell">
                        <div class="content-table__img"
                             style="background-image: url(<?= publicdir('images/players/photo_2.jpg') ?>)"></div>
                        <span>Сергей Иванов</span>
                    </div>
                    <div class="content-table__cell">498</div>
                </div>

                <div class="content-table__row on-top">
                    <div class="content-table__cell">3</div>
                    <div class="content-table__cell">
                        <div class="content-table__img"
                             style="background-image: url(<?= publicdir('images/players/photo_3.jpg') ?>)"></div>
                        <span>Константин Константинопольский</span>
                    </div>
                    <div class="content-table__cell">491</div>
                </div>

                <div class="content-table__row">
                    <div class="content-table__cell">4</div>
                    <div class="content-table__cell">
                        <div class="content-table__img"
                             style="background-image: url(<?= publicdir('images/players/photo_4.jpg') ?>)"></div>
                        <span>Dmitry Shkolovoy</span>
                    </div>
                    <div class="content-table__cell">470</div>
                </div>
                <div class="content-table__row">
                    <div class="content-table__cell">5</div>
                    <div class="content-table__cell">
                        <div class="content-table__img"
                             style="background-image: url(<?= publicdir('images/players/photo_1.jpg') ?>)"></div>
                        <span>Василий Малышкин</span>
                    </div>
                    <div class="content-table__cell">457</div>
                </div>

                <div class="content-table__row">
                    <div class="content-table__cell">6</div>
                    <div class="content-table__cell">
                        <div class="content-table__img"
                             style="background-image: url(<?= publicdir('images/players/photo_2.jpg') ?>)"></div>
                        <span>Сергей Иванов</span>
                    </div>
                    <div class="content-table__cell">450</div>
                </div>

                <div class="content-table__row">
                    <div class="content-table__cell">7</div>
                    <div class="content-table__cell">
                        <div class="content-table__img"
                             style="background-image: url(<?= publicdir('images/players/photo_1.jpg') ?>)"></div>
                        <span>Константин Константинопольский</span>
                    </div>
                    <div class="content-table__cell">440</div>
                </div>

                <div class="content-table__row">
                    <div class="content-table__cell">8</div>
                    <div class="content-table__cell">
                        <div class="content-table__img"
                             style="background-image: url(<?= publicdir('images/players/photo_1.jpg') ?>)"></div>
                        <span>Dmitry Shkolovoy</span>
                    </div>
                    <div class="content-table__cell">432</div>
                </div>
                <div class="content-table__row">
                    <div class="content-table__cell">9</div>
                    <div class="content-table__cell">
                        <div class="content-table__img"
                             style="background-image: url(<?= publicdir('images/players/photo_4.jpg') ?>)"></div>
                        <span>Dmitry Shkolovoy</span>
                    </div>
                    <div class="content-table__cell">15</div>
                </div>
                <div class="content-table__row">
                    <div class="content-table__cell">10</div>
                    <div class="content-table__cell">
                        <div class="content-table__img"
                             style="background-image: url(<?= publicdir('images/players/photo_1.jpg') ?>)"></div>
                        <span>Василий Малышкин</span>
                    </div>
                    <div class="content-table__cell">7</div>
                </div>

                <div class="content-table__row">
                    <div class="content-table__cell">11</div>
                    <div class="content-table__cell">
                        <div class="content-table__img"
                             style="background-image: url(<?= publicdir('images/players/photo_2.jpg') ?>)"></div>
                        <span>Сергей Иванов</span>
                    </div>
                    <div class="content-table__cell">4</div>
                </div>

                <div class="content-table__row">
                    <div class="content-table__cell">12</div>
                    <div class="content-table__cell">
                        <div class="content-table__img"
                             style="background-image: url(<?= publicdir('images/players/photo_1.jpg') ?>)"></div>
                        <span>Константин Константинопольский</span>
                    </div>
                    <div class="content-table__cell">0</div>
                </div>

                <div class="content-table__row">
                    <div class="content-table__cell">13</div>
                    <div class="content-table__cell">
                        <div class="content-table__img"
                             style="background-image: url(<?= publicdir('images/players/photo_1.jpg') ?>)"></div>
                        <span>Dmitry Shkolovoy</span>
                    </div>
                    <div class="content-table__cell">0</div>
                </div>
            </div>
        </div>

        <?php include "src/views/blocks/paging.phtml" ?>

</section>