<section class="page-caption">
    <div class="page-caption__logo">
        <a href="#"><img src="<?= publicdir('images/logo_1.png') ?>"/></a>
    </div>
    <div class="page-caption__text">
        <h2>Правила</h2>
    </div>
    <div class="page-caption__promo">
        <img src="<?= publicdir('images/rostelekom-logo-small.svg') ?>"><br>
        <span>Ростелеком</span>
    </div>
</section>
<section class="page-content">

    <ol class="page-content__instruction">
        <li><span><a href="#">Авторизуйся</a> через одну из социальных сетей и укажи
            свои эмоции.</span></li>
        <li><span><a href="#">Угадай</a> эмоции жителей «Уандерленда».</span></li>
        <li><span><a href="#">Играй</a> в суперигру зарабатывая баллы.</span></li>
        <li><span><a href="#">Укажи</a> номер договора с «Ростелеком» и получи +20 баллов!</span></li>
    </ol>
<div class="page-content__information">
    
    <ol class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <li class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading1">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse1" aria-expanded="false" aria-controls="collapse1">
                        <span>Общие положения</span>
                    </a>
                </h4>
            </div>
            <div id="collapse1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading1">
                <ol class="panel-body">
                    <li>Мероприятие проводится Обществом с ограниченной ответственностью «Фокс Фэкчуэл Чэннелс» (сокращенное наименование
                        – ООО «Фокс Фэкчуэл Чэннелс». Юридический адрес: 119435, Москва, ул. Малая Пироговская, д.16. Почтовый адрес: 119435,
                        Москва, ул. Малая Пироговская, д.16. ИНН 7704732229 и Обществом с ограниченной ответственностью «Артикул Медиа»
                        (сокращенное наименование — ООО «Артикул Медиа»). Юридический адрес: 123242 г. Москва, ул. Заморенова, д. 14/16, кв. 55.
                        Почтовый адрес: 105066 г. Москва, ул. Александра Лукьянова, д. 3. ИНН 7703501250</li>
                    <li>Сайт в сети Интернет, на которых будет размещена информация о проводимом Конкурсе — outcast.foxtv.ru.</li>
                </ol>
            </div>
        </li>
        <li class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading2">
                <h4 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse2" aria-expanded="false" aria-controls="collapse2">
                        <span>Сведения об организаторе мероприятия</span>
                    </a>
                </h4>
            </div>
            <div id="collapse2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
                <ol class="panel-body">
                    <li>Мероприятие проводится Обществом с ограниченной ответственностью «Фокс Фэкчуэл Чэннелс» (сокращенное наименование
                        – ООО «Фокс Фэкчуэл Чэннелс». Юридический адрес: 119435, Москва, ул. Малая Пироговская, д.16. Почтовый адрес: 119435,
                        Москва, ул. Малая Пироговская, д.16. ИНН 7704732229 и Обществом с ограниченной ответственностью «Артикул Медиа»
                        (сокращенное наименование — ООО «Артикул Медиа»). Юридический адрес: 123242 г. Москва, ул. Заморенова, д. 14/16, кв. 55.
                        Почтовый адрес: 105066 г. Москва, ул. Александра Лукьянова, д. 3. ИНН 7703501250</li>
                    <li>Сайт в сети Интернет, на которых будет размещена информация о проводимом Конкурсе — outcast.foxtv.ru.</li>
                </ol>
            </div>
        </li>
        <li class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading3">
                <h4 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse3" aria-expanded="false" aria-controls="collapse3">
                        <span>Сроки проведения мероприятия</span>
                    </a>
                </h4>
            </div>
            <div id="collapse3" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading3">
                <ol class="panel-body">
                    <li>Мероприятие проводится Обществом с ограниченной ответственностью «Фокс Фэкчуэл Чэннелс» (сокращенное наименование
                        – ООО «Фокс Фэкчуэл Чэннелс». Юридический адрес: 119435, Москва, ул. Малая Пироговская, д.16. Почтовый адрес: 119435,
                        Москва, ул. Малая Пироговская, д.16. ИНН 7704732229 и Обществом с ограниченной ответственностью «Артикул Медиа»
                        (сокращенное наименование — ООО «Артикул Медиа»). Юридический адрес: 123242 г. Москва, ул. Заморенова, д. 14/16, кв. 55.
                        Почтовый адрес: 105066 г. Москва, ул. Александра Лукьянова, д. 3. ИНН 7703501250</li>
                    <li>Сайт в сети Интернет, на которых будет размещена информация о проводимом Конкурсе — outcast.foxtv.ru.</li>
                </ol>
            </div>
        </li>
        <li class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading4">
                <h4 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse4" aria-expanded="false" aria-controls="collapse4">
                        <span>Участники мероприятия и их права</span>
                    </a>
                </h4>
            </div>
            <div id="collapse4" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading4">
                <ol class="panel-body">
                    <li>Мероприятие проводится Обществом с ограниченной ответственностью «Фокс Фэкчуэл Чэннелс» (сокращенное наименование
                        – ООО «Фокс Фэкчуэл Чэннелс». Юридический адрес: 119435, Москва, ул. Малая Пироговская, д.16. Почтовый адрес: 119435,
                        Москва, ул. Малая Пироговская, д.16. ИНН 7704732229 и Обществом с ограниченной ответственностью «Артикул Медиа»
                        (сокращенное наименование — ООО «Артикул Медиа»). Юридический адрес: 123242 г. Москва, ул. Заморенова, д. 14/16, кв. 55.
                        Почтовый адрес: 105066 г. Москва, ул. Александра Лукьянова, д. 3. ИНН 7703501250</li>
                    <li>Сайт в сети Интернет, на которых будет размещена информация о проводимом Конкурсе — outcast.foxtv.ru.</li>
                </ol>
            </div>
        </li>
        <li class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading5">
                <h4 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse5" aria-expanded="false" aria-controls="collapse5">
                        <span>Обязанности участников</span>
                    </a>
                </h4>
            </div>
            <div id="collapse5" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading5">
                <ol class="panel-body">
                    <li>Мероприятие проводится Обществом с ограниченной ответственностью «Фокс Фэкчуэл Чэннелс» (сокращенное наименование
                        – ООО «Фокс Фэкчуэл Чэннелс». Юридический адрес: 119435, Москва, ул. Малая Пироговская, д.16. Почтовый адрес: 119435,
                        Москва, ул. Малая Пироговская, д.16. ИНН 7704732229 и Обществом с ограниченной ответственностью «Артикул Медиа»
                        (сокращенное наименование — ООО «Артикул Медиа»). Юридический адрес: 123242 г. Москва, ул. Заморенова, д. 14/16, кв. 55.
                        Почтовый адрес: 105066 г. Москва, ул. Александра Лукьянова, д. 3. ИНН 7703501250</li>
                    <li>Сайт в сети Интернет, на которых будет размещена информация о проводимом Конкурсе — outcast.foxtv.ru.</li>
                </ol>
            </div>
        </li>
        <li class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading6">
                <h4 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse6" aria-expanded="false" aria-controls="collapse6">
                        <span>Размер, форма и количество наград</span>
                    </a>
                </h4>
            </div>
            <div id="collapse6" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading6">
                <ol class="panel-body">
                    <li>Мероприятие проводится Обществом с ограниченной ответственностью «Фокс Фэкчуэл Чэннелс» (сокращенное наименование
                        – ООО «Фокс Фэкчуэл Чэннелс». Юридический адрес: 119435, Москва, ул. Малая Пироговская, д.16. Почтовый адрес: 119435,
                        Москва, ул. Малая Пироговская, д.16. ИНН 7704732229 и Обществом с ограниченной ответственностью «Артикул Медиа»
                        (сокращенное наименование — ООО «Артикул Медиа»). Юридический адрес: 123242 г. Москва, ул. Заморенова, д. 14/16, кв. 55.
                        Почтовый адрес: 105066 г. Москва, ул. Александра Лукьянова, д. 3. ИНН 7703501250</li>
                    <li>Сайт в сети Интернет, на которых будет размещена информация о проводимом Конкурсе — outcast.foxtv.ru.</li>
                </ol>
            </div>
        </li>
        <li class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading7">
                <h4 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse7" aria-expanded="false" aria-controls="collapse7">
                        <span>Порядок вручения наград</span>
                    </a>
                </h4>
            </div>
            <div id="collapse7" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading7">
                <ol class="panel-body">
                    <li>Мероприятие проводится Обществом с ограниченной ответственностью «Фокс Фэкчуэл Чэннелс» (сокращенное наименование
                        – ООО «Фокс Фэкчуэл Чэннелс». Юридический адрес: 119435, Москва, ул. Малая Пироговская, д.16. Почтовый адрес: 119435,
                        Москва, ул. Малая Пироговская, д.16. ИНН 7704732229 и Обществом с ограниченной ответственностью «Артикул Медиа»
                        (сокращенное наименование — ООО «Артикул Медиа»). Юридический адрес: 123242 г. Москва, ул. Заморенова, д. 14/16, кв. 55.
                        Почтовый адрес: 105066 г. Москва, ул. Александра Лукьянова, д. 3. ИНН 7703501250</li>
                    <li>Сайт в сети Интернет, на которых будет размещена информация о проводимом Конкурсе — outcast.foxtv.ru.</li>
                </ol>
            </div>
        </li>
        <li class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading8">
                <h4 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse8" aria-expanded="false" aria-controls="collapse8">
                        <span>Способ и порядок информирования о сроках и условиях проведения мероприятия</span>
                    </a>
                </h4>
            </div>
            <div id="collapse8" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading8">
                <ol class="panel-body">
                    <li>Мероприятие проводится Обществом с ограниченной ответственностью «Фокс Фэкчуэл Чэннелс» (сокращенное наименование
                        – ООО «Фокс Фэкчуэл Чэннелс». Юридический адрес: 119435, Москва, ул. Малая Пироговская, д.16. Почтовый адрес: 119435,
                        Москва, ул. Малая Пироговская, д.16. ИНН 7704732229 и Обществом с ограниченной ответственностью «Артикул Медиа»
                        (сокращенное наименование — ООО «Артикул Медиа»). Юридический адрес: 123242 г. Москва, ул. Заморенова, д. 14/16, кв. 55.
                        Почтовый адрес: 105066 г. Москва, ул. Александра Лукьянова, д. 3. ИНН 7703501250</li>
                    <li>Сайт в сети Интернет, на которых будет размещена информация о проводимом Конкурсе — outcast.foxtv.ru.</li>
                </ol>
            </div>
        </li>
        <li class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading9">
                <h4 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse9" aria-expanded="false" aria-controls="collapse9">
                        <span>Порядок хранения невостребованной награды и порядок ее востребования</span>
                    </a>
                </h4>
            </div>
            <div id="collapse9" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading9">
                <ol class="panel-body">
                    <li>Мероприятие проводится Обществом с ограниченной ответственностью «Фокс Фэкчуэл Чэннелс» (сокращенное наименование
                        – ООО «Фокс Фэкчуэл Чэннелс». Юридический адрес: 119435, Москва, ул. Малая Пироговская, д.16. Почтовый адрес: 119435,
                        Москва, ул. Малая Пироговская, д.16. ИНН 7704732229 и Обществом с ограниченной ответственностью «Артикул Медиа»
                        (сокращенное наименование — ООО «Артикул Медиа»). Юридический адрес: 123242 г. Москва, ул. Заморенова, д. 14/16, кв. 55.
                        Почтовый адрес: 105066 г. Москва, ул. Александра Лукьянова, д. 3. ИНН 7703501250</li>
                    <li>Сайт в сети Интернет, на которых будет размещена информация о проводимом Конкурсе — outcast.foxtv.ru.</li>
                </ol>
            </div>
        </li>
        <li class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading10">
                <h4 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse10" aria-expanded="false" aria-controls="collapse10">
                        <span>Дополнительные условия</span>
                    </a>
                </h4>
            </div>
            <div id="collapse10" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading10">
                <ol class="panel-body">
                    <li>Мероприятие проводится Обществом с ограниченной ответственностью «Фокс Фэкчуэл Чэннелс» (сокращенное наименование
                        – ООО «Фокс Фэкчуэл Чэннелс». Юридический адрес: 119435, Москва, ул. Малая Пироговская, д.16. Почтовый адрес: 119435,
                        Москва, ул. Малая Пироговская, д.16. ИНН 7704732229 и Обществом с ограниченной ответственностью «Артикул Медиа»
                        (сокращенное наименование — ООО «Артикул Медиа»). Юридический адрес: 123242 г. Москва, ул. Заморенова, д. 14/16, кв. 55.
                        Почтовый адрес: 105066 г. Москва, ул. Александра Лукьянова, д. 3. ИНН 7703501250</li>
                    <li>Сайт в сети Интернет, на которых будет размещена информация о проводимом Конкурсе — outcast.foxtv.ru.</li>
                </ol>
            </div>
        </li>
    </ol>
</div>
</section>