<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title></title>

<?php /* favicon by default is turned off 
<link rel="shortcut icon" href="<?= publicdir('favicon.ico') ?>">
<link rel="icon" type="image/png" href="<?= publicdir('favicon.png') ?>">
*/ ?>

<?php include "helpers/meta.phtml" ?>
<?php include "helpers/assets-css.phtml" ?>

<!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script>window.html5 || document.write('<script src="<?= publicdir("vendor/html5shiv.min.js") ?>"><\/script>')</script>
<![endif]-->
</head>
<body class="page page-<?= $page ?>">
    <div class="layout-wrapper">
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->


        <?php include "helpers/header.phtml" ?>
        <!-- .layout-header -->

        <!-- .blocs for game pages -->
        <main class="layout-main content-<?= $page; ?>">
            <?php if (strpos($page, 'game-scene') !== false): ?>
                <?php include "src/views/blocks/authorised-user.phtml" ?>
                <?php include "src/views/blocks/scene-aside.phtml" ?>
            <?php endif; ?>
            <?php include "pages/" . $page . ".phtml" ; ?>
        </main><!-- .layout-main -->

        <?php if (strpos($page, 'game-scene') !== false): ?>
            <?php include "src/views/blocks/footer-share.phtml" ?>
        <?php endif; ?>


        <?php include "helpers/footer.phtml" ?>
        <!-- .layout-footer -->
    </div><!-- .layout-wrapper -->

    <?php include "helpers/assets-js.phtml" ?>
</body>
</html>
