<!-- set here class="a-user unautorized" to hide panel at all-->
<div class="a-user">
	<div class="a-user-bookmark" data-toggle="collapse" data-target="#user-panel" id="user-bookmark">
		<div class="a-user-pic">
			<div class="a-user-pic__wrap">
				<img class="a-user-pic__img" src="">
			</div>
			<span class="a-user__soc-network facebook"></span>
		</div>
		<div class="a-user-info">
			<span class="a-user-info__points">0</span>
			<span class="a-user-info__units">баллов</span>
		</div>
	</div>
	<div class="a-user-panel collapse width" id="user-panel">
		<div class="a-user-panel__wrap">
			<div class="a-user__name">Константин Константинопольский</div>
			<div class="a-user-bookmark a-user-bookmark--inside" data-toggle="collapse" data-target="#user-panel">
				<div class="a-user-pic">
					<div class="a-user-pic__wrap">
						<img class="a-user-pic__img" src="">
					</div>
					<span class="a-user__soc-network facebook"></span>
				</div>
				<div class="a-user-info">
					<span class="a-user-info__points">0</span>
					<span class="a-user-info__units">баллов</span>
				</div>
				<div class="a-user-rating">
					<span class="a-user-rating__place">37</span>
					<span class="a-user-rating__unit">место</span>
				</div>
				<div class="a-user__logout">
					<a href="#" class="btn btn-default">Выйти</a>
				</div>
			</div>
			<div class="a-user__scrollable">
				<div class="a-user-supergame">
					<a href="#superGame" class="btn btn-default a-user-supergame__btn" data-toggle="modal">Суперигра</a>
				</div>
				<div class="a-user-traits">
					<div class="a-user-traits__wrap">
						<div id="user-traits-container"></div>
					</div>
					<?php include "src/views/templates/user-traits.phtml" ?>
				</div>
				<div class="a-user-agreement">
					<div class="a-user-agreement__start" id="agreement-start">
						<div class="a-user-agreement__text">Введите № договора с «Ростелеком»,
							чтоб получить +20 бонусов</div>
						<div class="a-user-agreement__enter" id="agreement-offer">
							<img class="rostelekom-logo-small" src="<?= publicdir('images/rostelekom-logo-small.svg') ?>">
							<a href="#" class="btn btn-default a-user-agreement__btn" id="enter-agreement-num">Ввести номер договора</a>
						</div>
						<form class="form-inline a-user-agreement-form" id="agreement-form" method="POST" action="/api/user-set-contract/">
							<div class="form-group">
								<div class="input-group">
									<div class="input-group-addon">
										<img class="rostelekom-logo-small" src="<?= publicdir('images/rostelekom-logo-small.svg') ?>">
									</div>
									<input class="form-control" type="text" name="number"
										   data-rule-required="true"
										   data-msg-required="Заполните поле"
										   data-rule-minlength="8"
										   data-msg-minlength="Минимум 8 цифр"
										   data-rule-digits="true"
										   data-msg-digits="Допустимы только цифры"
									>
								</div>
								<button type="submit" class="btn btn-primary a-user-agreement-form__btn">OK</button>
							</div>
						</form>
						<div class="a-user-agreement__success" id="agreement-success">
							<img class="rostelekom-logo-small" src="<?= publicdir('images/rostelekom-logo-small.svg') ?>">
							<span class="a-user-agreement__text">Поздравляем!</span>
						</div>
						<div class="a-user-agreement__error" id="agreement-error">
							<div class="a-user-agreement__text">Произошла ошибка. Попробовать еще&nbsp;раз?</div>
							<a href="#" class="btn btn-primary" id="agreement-try-again">Да</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>