<div class="a-user">
	<div class="a-user-bookmark" data-toggle="collapse" data-target="#user-panel" id="user-bookmark">
		<div class="a-user-pic">
			<div class="a-user-pic__wrap">
				<img class="a-user-pic__img" src="">
			</div>
			<span class="a-user__soc-network facebook"></span>
		</div>
		<div class="a-user-info">
			<span class="a-user-info__points">0</span>
			<span class="a-user-info__units">баллов</span>
		</div>
	</div>
	<div class="a-user-panel collapse width" id="user-panel">
		<div class="a-user-panel__wrap">
			<div class="a-user-bookmark a-user-bookmark--inside" data-toggle="collapse" data-target="#user-panel">
				<div class="a-user-pic">
					<div class="a-user-pic__wrap">
						<img class="a-user-pic__img" src="">
					</div>
					<span class="a-user__soc-network facebook"></span>
				</div>
				<div class="a-user-info">
					<span class="a-user-info__points">0</span>
					<span class="a-user-info__units">баллов</span>
				</div>
			</div>
		</div>
	</div>
</div>