<div class="characteristics">

    <div class="characteristic">
        <div class="smile"><img src="<?= publicdir('images/faces/face1.svg') ?>"></div>
        <div class="title">Гордый</div>
        <div class="value">+10</div>
    </div>
    <div class="characteristic">
        <div class="smile"><img src="<?= publicdir('images/faces/face2.svg') ?>"></div>
        <div class="title">Деликатный</div>
        <div class="value"><i class="icon icon-minus"></i></div>
    </div>
    <div class="characteristic">
        <div class="smile"><img src="<?= publicdir('images/faces/face3.svg') ?>"></div>
        <div class="title">Гордый</div>
        <div class="value"><i class="icon icon-tick"></i></div>
    </div>
    <div class="characteristic">
        <div class="smile"><img src="<?= publicdir('images/faces/face4.svg') ?>"></div>
        <div class="title">Деликатный</div>
        <div class="value">+7</div>
    </div>
</div>