<div class="heart-block" style="top: 200px; left: 500px;">
    <a href="#" class="heart-icon"data-toggle="collapse" data-target="#heart1">
        <img src="<?= publicdir('images/heart-icon.svg') ?>">
    </a>
    <div class="result">
        <span>3</span>
    </div>
    <div class="popup popup--heart collapse" id="heart1">

        <div class="popup-body">
            <div class="popup-header">
                <div class="photo" style="background-image: url(<?= publicdir('images/photo_1.jpg') ?>)">
                </div>
                <div class="name">Карлос</div>
            </div>
            <div class="popup-close"></div>
            <div class="popup-content">
                <div class="characteristic">
                    <div class="smile"><img src="<?= publicdir('images/faces/face1.svg') ?>"></div>
                    <div class="title">Гордый</div>
                    <div class="value">+10</div>
                </div>
                <div class="characteristic">
                    <div class="smile"><img src="<?= publicdir('images/faces/face2.svg') ?>"></div>
                    <div class="title">Деликатный</div>
                    <div class="value"><i class="icon icon-minus"></i></div>
                </div>
                <div class="characteristic">
                    <div class="smile"><img src="<?= publicdir('images/faces/face4.svg') ?>"></div>
                    <div class="title">Деликатный</div>
                    <div class="value">+7</div>
                </div>
                <div class="characteristic">
                    <div class="smile"><img src="<?= publicdir('images/faces/face4.svg') ?>"></div>
                    <div class="title">Деликатный</div>
                    <div class="value">+7</div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="heart-block" style="top: 500px; left: 300px;">
    <a href="#" class="heart-icon"data-toggle="collapse" data-target="#heart2">
        <img src="<?= publicdir('images/heart-icon.svg') ?>">
    </a>
    <div class="popup popup--heart collapse" id="heart2">

        <div class="popup-body">
            <div class="popup-header">
                <div class="photo" style="background-image: url(<?= publicdir('images/photo_1.jpg') ?>)">
                </div>
                <div class="name">Карлос</div>
            </div>
            <div class="popup-close"></div>
            <div class="popup-content">
                <p>Известен своими скоростными данными и особо сильными дальними ударами,
                    с которых забил немало голов, в том числе со штрафных. В 1997 году занял
                    второе место по результатам голосования по присуждению звания игрока года ФИФА,
                    уступив соотечественнику Роналдо.</p>
            </div>
            <div class="popup-footer">
                <a class="btn btn-primary">Угадать черты характера</a>
            </div>
        </div>
    </div>
</div>
<div class="heart-block" style="top: 100px; left: 1200px;">
    <a href="#" class="heart-icon"><img src="<?= publicdir('images/heart-icon.svg') ?>"></a>
</div> 