<div class="paging" xmlns="http://www.w3.org/1999/html">
    <div class="paging-wrap">
        <a href="#" class="paging__ctrl paging__ctrl--prev disabled"></a>
        <ul class="paging__list">
            <li class="paging__item active">1</li>
            <li class="paging__item"><a href="#">2</a></li>
            <li class="paging__item"><a href="#">3</a></li>
            <li class="paging__item"><a href="#">4</a></li>
            <li class="paging__item"><a href="#">5</a></li>
            <li class="paging__divider">...</li>
            <li class="paging__item"><a href="#">10</a></li>
        </ul>
        <a href="#" class="paging__ctrl paging__ctrl--next"></a>
    </div>
</div>