<aside class="scene-aside">
	<nav class="scene-navs">
		<ul class="scene-links">
			<li class="scene-links__i">
				<a href="#" class="scene-links__lk">
					<i class="icon icon-info"></i>
					<span class="scene-links__text">Прочитать<br>текст</span>
				</a>
			</li>
			<li class="scene-links__i">
				<a href="#" class="scene-links__lk">
					<i class="icon icon-video"></i>
					<span class="scene-links__text">Посмотреть<br>видео</span>
				</a>
			</li>
		</ul>
	</nav>
	<div class="rostelekom scene-aside__partner">
		<img class="rostelekom-logo" src="<?= publicdir('images/rostelekom-logo-big.svg') ?>">
		<a href="#" class="btn btn-primary rostelekom__btn">Подключить</a>
	</div>
</aside>