
<div class="modal fade" id="superGame" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header"><button class="close" type="button" data-dismiss="modal"><i class="icon icon-cross"></i></button>
                <div class="modal-title">Расставь черты характера по аватару</div>
            </div>
            <div class="modal-body">
                <?php
                include "src/views/blocks/users.phtml" ?>
            </div>
            <a class="btn btn-primary modal__btn">Готово</a>
        </div>

    </div>