<div class="modal fade" id="superGame" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" type="button" data-dismiss="modal"><i class="icon icon-cross"></i></button>
                <div class="modal-title">Выбор черт характера</div>
            </div>
            <div class="modal-body">
                <div class="user">
                    <div class="user__header">
                        <div class="user__image"
                             style="background-image: url(<?= publicdir('images/players/photo_2.jpg') ?>)"></div>
                        <span class="user__name">Константин<br> Константинопольский</span>
                    </div>
                    <form method="post">
                        <div class="user__option">
                            <div class="characteristic">
                                <input type="checkbox" id="ch_6" name="characteristic"/>
                                <label for="ch_6">
                                    <span class="smile"><img src="<?= publicdir('images/faces/face1.svg') ?>"></span>
                                    <span class="title">Деликатный</span>
                                    <span class="value"><i class="icon icon-tick"></i></span>
                                </label>
                            </div>
                            <div class="characteristic">
                                <input type="checkbox" id="ch_7" name="characteristic"/>
                                <label for="ch_7">
                                    <span class="smile"><img src="<?= publicdir('images/faces/face2.svg') ?>"></span>
                                    <span class="title">Гордый</span>
                                    <span class="value"><i class="icon icon-tick"></i></span>
                                </label>
                            </div>
                            <div class="characteristic">
                                <input type="checkbox" id="ch_8" name="characteristic"/>
                                <label for="ch_8">
                                    <span class="smile"><img src="<?= publicdir('images/faces/face3.svg') ?>"></span>
                                    <span class="title">Деликатный</span>
                                    <span class="value"><i class="icon icon-tick"></i></span>
                                </label>
                            </div>
                            <div class="characteristic">
                                <input type="checkbox" id="ch_9" name="characteristic"/>
                                <label for="ch_9">
                                    <span class="smile"><img src="<?= publicdir('images/faces/face4.svg') ?>"></span>
                                    <span class="title">Гордый</span>
                                    <span class="value"><i class="icon icon-tick"></i></span>
                                </label>
                            </div>
                            <div class="characteristic">
                                <input type="checkbox" id="ch_10" name="characteristic"/>
                                <label for="ch_10">
                                    <span class="smile"><img src="<?= publicdir('images/faces/face1.svg') ?>"></span>
                                    <span class="title">Деликатный</span>
                                    <span class="value"><i class="icon icon-tick"></i></span>
                                </label>
                            </div>
                        </div>

                        <div class="user__option">
                            <div class="characteristic">
                                <input type="checkbox" id="ch_11" name="characteristic"/>
                                <label for="ch_11">
                                    <span class="smile"><img src="<?= publicdir('images/faces/face1.svg') ?>"></span>
                                    <span class="title">Деликатный</span>
                                    <span class="value"><i class="icon icon-tick"></i></span>
                                </label>
                            </div>
                            <div class="characteristic">
                                <input type="checkbox" id="ch_12" name="characteristic"/>
                                <label for="ch_12">
                                    <span class="smile"><img src="<?= publicdir('images/faces/face2.svg') ?>"></span>
                                    <span class="title">Гордый</span>
                                    <span class="value"><i class="icon icon-tick"></i></span>
                                </label>
                            </div>
                            <div class="characteristic">
                                <input type="checkbox" id="ch_13" name="characteristic"/>
                                <label for="ch_13">
                                    <span class="smile"><img src="<?= publicdir('images/faces/face3.svg') ?>"></span>
                                    <span class="title">Деликатный</span>
                                    <span class="value"><i class="icon icon-tick"></i></span>
                                </label>
                            </div>
                            <div class="characteristic">
                                <input type="checkbox" id="ch_14" name="characteristic"/>
                                <label for="ch_14">
                                    <span class="smile"><img src="<?= publicdir('images/faces/face4.svg') ?>"></span>
                                    <span class="title">Гордый</span>
                                    <span class="value"><i class="icon icon-tick"></i></span>
                                </label>
                            </div>
                            <div class="characteristic">
                                <input type="checkbox" id="ch_15" name="characteristic"/>
                                <label for="ch_15">
                                    <span class="smile"><img src="<?= publicdir('images/faces/face1.svg') ?>"></span>
                                    <span class="title">Деликатный</span>
                                    <span class="value"><i class="icon icon-tick"></i></span>
                                </label>
                            </div>
                        </div>
                        <input class="btn btn-primary user__btn" type="submit" value="Подтвердить">
                    </form>
                </div>

            </div>