<div class="user">
    <div class="user__header">
        <div class="user__image" style="background-image: url(<?= publicdir('images/players/photo_2.jpg') ?>)"></div>
        <span class="user__name">Константин<br> Константинопольский</span>
    </div>
    <div class="user__content">
        <div class="characteristic">
            <div class="smile"><img src="<?= publicdir('images/faces/face1.svg') ?>"></div>
            <div class="title">Гордый</div>
            <div class="value">+10</div>
        </div>
        <div class="characteristic">
            <div class="smile"><img src="<?= publicdir('images/faces/face2.svg') ?>"></div>
            <div class="title">Деликатный</div>
            <div class="value"><i class="icon icon-minus"></i></div>
        </div>
        <div class="characteristic">
            <div class="smile"><img src="<?= publicdir('images/faces/face2.svg') ?>"></div>
            <div class="title">Деликатный</div>
            <div class="value"><i class="icon icon-minus"></i></div>
        </div>
        <div class="characteristic">
            <div class="smile"><img src="<?= publicdir('images/faces/face4.svg') ?>"></div>
            <div class="title">Деликатный</div>
            <div class="value">+7</div>
        </div>
        <div class="characteristic">
            <div class="smile"><img src="<?= publicdir('images/faces/face4.svg') ?>"></div>
            <div class="title">Деликатный</div>
            <div class="value">+7</div>
        </div>
    </div>
</div>
<div class="user">
    <div class="user__header">
        <div class="user__image" style="background-image: url(<?= publicdir('images/players/photo_3.jpg') ?>)"></div>
        <span class="user__name">Илья<br> Рогозов</span>
    </div>
    <div class="user__content">
        <a class="btn btn-primary">Угадать черты характера</a>
    </div>
</div>
<div class="user">
    <div class="user__header">
        <div class="user__image" style="background-image: url(<?= publicdir('images/players/photo_4.jpg') ?>)"></div>
        <span class="user__name">Мария<br> Мастяева</span>
    </div>
    <div class="user__content">
        <a class="btn btn-primary">Угадать черты характера</a>
    </div>
</div>