<div class="modal fade" id="superGame" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button class="close" type="button" data-dismiss="modal"><i class="icon icon-cross"></i></button>
				<div class="modal-title">Расставь черты характера по аватару</div>
			</div>
			<div class="modal-body">
				<div id="extraround-target"></div>
			</div>
			<a class="btn btn-primary modal__btn">Готово</a>
		</div>
	</div>
</div>

<div id="extraround-user-popup-target"></div>


<script type="text/template" id="extraround-template">
	<% _.each(users, function(user, key, list){
	var target = '#sg-'+key;
	%>
	<div class="user">
		<div class="user__header">
			<div class="user__image"><img src="<%= user.image %>"></div>
			<span class="user__name"><%= user.name %></span>
		</div>
		<div class="user__content" data-user-offer>
			<a class="btn btn-primary" data-toggle="modal" data-target="<%= target %>">Угадать черты характера</a>
		</div>
		<div class="user__content" data-user-result style="display: none;">
			<!-- answered -->
			<div class="traits traits--result" data-nicescroll-block>
				<% _.each(traits, function(trait,key,list){ %>
				<div class="trait" data-trait-id="<%= key %>">
					<div class="trait__smile"><img src="build/images/<%= trait.image %>"></div>
					<div class="trait__title"><%= trait.name %></div>
					<div class="trait__value" data-trait-result></div>
				</div>
				<% }); %>
			</div>
		</div>
	</div>
	<% }); %>
</script>
<script type="text/template" id="extraround-user-template">
	<!-- modals for users here: -->
	<% _.each(users, function(user, key, list){
	var target = 'sg-'+key;
	%>
	<div class="modal fade" id="target" tabindex="-1" role="dialog">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				<div class="modal-header">
					<button class="close" type="button" data-dismiss="modal"><i class="icon icon-cross"></i></button>
					<div class="modal-title">Выбор черт характера</div>
				</div>
				<div class="modal-body">
					<div class="user">
						<div class="user__header">
							<div class="user__image"><img src="<%= user.image %>"></div>
							<span class="user__name"><%= user.name %></span>
						</div>
					</div>
					<div class="user__traits">
						<form>
							<input type="text" style="display: none;" name="characterid" value="<%=user.id%>">
							<div class="traits" data-nicescroll-block>
								<% _.each(traits, function(trait, key, list){
								var uid = item.code + key;
								%>
								<div class="trait">
									<input type="checkbox" id="ch_<%= uid %>" name="traits" value="<%= key %>">
									<label for="ch_<%= uid %>">
										<div class="trait__smile"><img src="build/images/<%= trait.image %>"></div>
										<div class="trait__title"><%= trait.name %></div>
										<span class="trait__value"><i class="icon icon-tick"></i></span>
								</div>
								<% }); %>
							</div>

							<input class="btn btn-primary user__btn" type="submit" value="Подтвердить">
						</form>
					</div>
				</div>

			</div>
			<% }); %>
</script>