<div class="modal fade" id="superGame" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button class="close" type="button" data-dismiss="modal"><i class="icon icon-cross"></i></button>
				<div class="modal-title">Расставь черты характера по аватару</div>
			</div>
			<div class="modal-body">
				<a href="#" data-user-arrow="left" class="scene-arrow scene-arrow__left"></a>
				<a href="#" data-user-arrow="right" class="scene-arrow scene-arrow__right"></a>
				<div id="extraround-target" class="users-slider"></div>
			</div>
			<a class="btn btn-primary modal__btn">Готово</a>
		</div>
	</div>
</div>

<div id="extraround-user-popup-target"></div>


<script type="text/template" id="extraround-template">

	<% _.each(users, function(user, key, list){
	var target = '#sg-'+user.id;
	%>
	<div class="user" data-id="<%= target %>">
		<div class="user__header">
			<div class="user__image"><img src="/build/images/<%= user.image %>"></div>
			<span class="user__name"><%= user.name %></span>
		</div>
		<div class="user__content" data-user-offer>
			<a class="btn btn-primary" data-toggle="modal" data-target="<%= target %>"
			<% if (user.nopopup) { %>
				style="display:none;"
			<% } %>
			>Угадать черты характера</a>
		</div>
		<div class="user__content" data-user-result data-nicescroll-block
			<% if (!user.nopopup) { %>
				style="display:none;"
			<% } %>
		>
			<!-- answered -->
			<div class="traits traits--result" data-nicescroll-inner>
				<% _.each(user.traits, function(trait,key,list){ %>
				<div class="trait" data-trait-id="<%= key %>"
				>
					<div class="trait__smile"><img src="build/images/<%= trait.image %>"></div>
					<div class="trait__title"><%= trait.name %></div>
					<div class="trait__value" data-trait-result>
						<% if (trait.state == 'incorrect') { %>
							<i class="icon icon-minus"></i>
						<% } else if (trait.state == 'correct') {%>
							+1
						<% } %>
					</div>
				</div>
				<% }); %>
			</div>
		</div>
	</div>
	<% }); %>

</script>
<script type="text/template" id="extraround-user-template">
	<!-- modals for users here: -->
	<% _.each(users, function(user, key, list){
	var target = 'sg-'+user.id;
	%>
	<% if (!user.nopopup) { %>

	<div class="modal fade" id="<%= target %>" tabindex="-1" role="dialog" data-modal-user-choose>
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				<div class="modal-header">
					<button class="close" type="button" data-dismiss="modal"><i class="icon icon-cross"></i></button>
					<div class="modal-title">Выбор черт характера</div>
				</div>
				<div class="modal-body">
					<div class="user user--single">
						<div class="user__header">
							<div class="user__image"><img src="/build/images/<%= user.image %>"></div>
							<span class="user__name"><%= user.name %></span>
						</div>
						<div class="user__traits" data-user-traits-choose>
							<form class="user__form">
								<input type="text" style="display: none;" name="characterid" value="<%=user.id%>">
								<div class="traits traits--tall" data-nicescroll-block>
									<% _.each(user.traits, function(trait, key, list){
									var uid = user.id + key;
									%>
									<div class="trait">
										<input type="checkbox" id="ch_<%= uid %>" name="traits" value="<%= key %>">
										<label for="ch_<%= uid %>">
											<div class="trait__smile"><img src="build/images/<%= trait.image %>"></div>
											<div class="trait__title"><%= trait.name %></div>
											<span class="trait__value"><i class="icon icon-tick"></i></span>
									</div>
									<% }); %>
								</div>

								<button class="btn btn-primary user__btn" type="submit">Подтвердить</button>
							</form>
						</div>
						<div class="user__traits" data-user-traits-error style="display:none;">
							<div class="a-user-choose__head" data-head>Произошла ошибка.</div>
							<a href="#" class="btn btn-primary btn-fullwidth" data-again>Заполнить еще раз</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
			<% } %>
			<% }); %>
</script>


<!-- Modal -->
<div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Произошла ошибка</h4>
			</div>
			<div class="modal-body">
				Произошла ошибка. Перезагрузите стараницу и попробуйте еще раз.
			</div>
		</div>
	</div>
</div>