<div id="header-target"></div>

<script type="text/template" id="header-template">
	<header class="scene-header">
		<div class="caption">Сцена <%=id%>: <b><%=name%></b></div>
		<div class="explain active">Изучите сцену. <a href="#" data-to-step="2">Дальше</a></div>
		<div class="explain">Угадайте эмоции персонажа из этой сцены. <a href="#" data-target="#superGame" data-toggle="modal">Дальше</a></div>
	</header>
</script>