<div id="header-target"></div>

<script type="text/template" id="header-template">
	<header class="scene-header">
		<div class="caption">Сцена <%=id%>. <b>Угадай эмоции героев</b></div>
<div class="explain active"><!--Изучите сцену. <a href="#" data-to-step="2">Дальше</a>--></div>
		<div class="explain"> <a class="btn btn-primary" href="#superGame" data-toggle="modal">Играть</a></div>

	</header>
</script>