

<script type="text/template" id="user-traits-template">
	<!-- checkboxes here-->
	<div class="a-user-choose" data-self-start>
		<div class="a-user-choose__head">Выбрать мои 5 черт<br>характера</div>
		<a href="#"  class="btn btn-primary btn-fullwidth" data-goto-selfchose>Выбрать</a>
	</div>
	<div class="a-user-choose" data-self-choose style="display:none;">
		<div class="a-user-choose__head">Мои 5 черт<br>характера:</div>
		<form>
				<div class="traits">
			<% _.each(traits, function(trait, key, list){
				var uid = 'user' + key;

				%>

				<div class="trait">
					<input type="checkbox" id="ch_<%= uid %>" name="traits" value="<%= key %>">
					<label for="ch_<%= uid %>">
					<div class="trait__smile"><img src="build/images/<%= trait.image %>"></div>
					<div class="trait__title"><%= trait.name %></div>
					<span class="trait__value"><i class="icon icon-tick"></i></span>
					</div>
					<% }); %>
			</div>
			<button type="submit" class="btn btn-primary btn-fullwidth">Подтвердить</button>
		</form>
	</div>
	<div class="a-user-choose" data-self-result style="display:none;">
		<div class="a-user-choose__head">Мои 5 черт<br>характера</div>
		<!-- answer will be here -->
		<div class="traits traits--result">
			<% _.each(traits, function(trait,key,list){ %>
			<div class="trait" data-trait-id="<%= key %>">
				<div class="trait__smile"><img src="build/images/<%= trait.image %>"></div>
				<div class="trait__title"><%= trait.name %></div>
			</div>
			<% }); %>
		</div>
	</div>
	<div class="a-user-choose" data-self-error style="display:none;">
		<div class="a-user-choose__head" data-head>Произошла ошибка.</div>
		<a href="#" class="btn btn-primary btn-fullwidth" data-again>Заполнить еще раз</a>
	</div>
</script>